name: Get Feed

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  get-feed:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python extract_hackaday.py
      - name: Make files
        run: python make_files.py
      - name: commit feed
        continue-on-error: true
        run: |
          git config user.name  "inajob"
          git config user.email "inajob@users.noreply.github.com"
          git add .
          git commit -m "`date`"
          git push
      - name: call OpenAI
        run: sh process_all.sh
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
      - name: commit feed again
        continue-on-error: true
        run: |
          git config user.name  "inajob"
          git config user.email "inajob@users.noreply.github.com"
          git add .
          git commit -m "`date`"
          git push

